### ISSUE TITLE
springboot项目引入maven后，测试的时候Message类导包的时候没有对应的包

### ISSUE THREAD

**Issue by KlaywwW** [wxpusher/wxpusher-sdk-java#3]
![image](https://user-images.githubusercontent.com/56384695/97988259-a5392980-1e17-11eb-96ee-c5716a302766.png)
![image](https://user-images.githubusercontent.com/56384695/97988275-ac603780-1e17-11eb-9c95-f68520d78a19.png)

**Comment by KlaywwW** [comment]
请问怎么使用时，谢谢

**Comment by KlaywwW** [comment]
已经解决了，将dependency里的type去掉就可以了，真的很好用，谢谢！

**Comment by KlaywwW** [comment]
.

**Comment by hackedbyxx** [comment]
文档还没改，看了你的才明白
